// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/medication_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7490321166854779770),
      name: 'Medication',
      lastPropertyId: const IdUid(4, 883090518237764244),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4447966928412672079),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 9144144104658495704),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 9061892704017251231),
            name: 'dosage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 883090518237764244),
            name: 'additionalInfo',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7490321166854779770),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Medication: EntityDefinition<Medication>(
        model: _entities[0],
        toOneRelations: (Medication object) => [],
        toManyRelations: (Medication object) => {},
        getId: (Medication object) => object.id,
        setId: (Medication object, int id) {
          object.id = id;
        },
        objectToFB: (Medication object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final dosageOffset = fbb.writeString(object.dosage);
          final additionalInfoOffset = fbb.writeString(object.additionalInfo);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, dosageOffset);
          fbb.addOffset(3, additionalInfoOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final dosageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final additionalInfoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final object = Medication(
              id: idParam,
              name: nameParam,
              dosage: dosageParam,
              additionalInfo: additionalInfoParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Medication] entity fields to define ObjectBox queries.
class Medication_ {
  /// see [Medication.id]
  static final id =
      QueryIntegerProperty<Medication>(_entities[0].properties[0]);

  /// see [Medication.name]
  static final name =
      QueryStringProperty<Medication>(_entities[0].properties[1]);

  /// see [Medication.dosage]
  static final dosage =
      QueryStringProperty<Medication>(_entities[0].properties[2]);

  /// see [Medication.additionalInfo]
  static final additionalInfo =
      QueryStringProperty<Medication>(_entities[0].properties[3]);
}
